## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_clean = application_df.copy()
application_clean = application_df.drop(columns=["EIN", "NAME"])
application_clean.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_clean.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_clean["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_clean['APPLICATION_TYPE'].value_counts()[application_clean['APPLICATION_TYPE'].value_counts() < 200].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_clean['APPLICATION_TYPE'] = application_clean['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_clean['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_clean["CLASSIFICATION"].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
# Count occurrences of each classification
classification_counts = application_clean['CLASSIFICATION'].value_counts()

# Filter classifications with count greater than 1
classification_counts_greater_than_1 = classification_counts[classification_counts > 1]
classification_counts_greater_than_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = application_clean['APPLICATION_TYPE'].value_counts()[application_clean['APPLICATION_TYPE'].value_counts() < 1000].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_clean['CLASSIFICATION'] = application_clean['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_clean['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_clean[['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']], dtype=int)
application_clean = pd.concat([application_clean, application_dummies], axis=1)
application_clean.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1,...,0,0,0,0,0,0,0,0,1,0
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1,...,1,0,0,0,0,0,0,0,1,0
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0,...,0,0,0,0,0,0,0,0,1,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1,...,0,1,0,0,0,0,0,0,1,0
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# The following is from chatGPT after getting an error about non-numeric columns
# Check for any non-numeric columns
non_numeric_columns = application_clean.select_dtypes(include=['object']).columns
print(non_numeric_columns)

Index(['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'],
      dtype='object')

In [11]:
# Drop any non-numeric columns
application_clean = application_clean.drop(columns=['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'])
application_clean.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [12]:
# Split our preprocessed data into our features and target arrays
y = application_clean["IS_SUCCESSFUL"]
X = application_clean.drop(columns = "IS_SUCCESSFUL")

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    random_state=1)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [38]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# First hidden layer with Leaky ReLU activation
nn_model.add(tf.keras.layers.Dense(units=64, activation=tf.keras.layers.LeakyReLU(alpha=0.01), input_dim=108, kernel_initializer="VarianceScaling"))

# Second hidden layer with ELU activation
nn_model.add(tf.keras.layers.Dense(units=32, activation=tf.keras.layers.ELU(), kernel_initializer="VarianceScaling"))

# Third hidden layer with Tanh activation
nn_model.add(tf.keras.layers.Dense(units=16, activation="tanh", kernel_initializer="VarianceScaling"))

# Output layer with Sigmoid activation for binary classification
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid", kernel_initializer="VarianceScaling"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 64)                6976

 dense_13 (Dense)            (None, 32)                2080

 dense_14 (Dense)            (None, 16)                528

 dense_15 (Dense)            (None, 1)                 17

=================================================================
Total params: 9601 (37.50 KB)
Trainable params: 9601 (37.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the filepath for saving the model weights
checkpoint_filepath = 'model_weights.h5'

# Create a callback to save the model's weights every five epochs
checkpoint_callback = ModelCheckpoint(filepath=checkpoint_filepath,
                                      save_weights_only=True,
                                      save_freq='epoch',  # Save every epoch
                                      period=5)           # Save every five epochs

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [40]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [41]:

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5675 - accuracy: 0.7205
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5517 - accuracy: 0.7312
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7320
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7311
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7325
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7326
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7328
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7343
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7340
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7353
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7359
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7348
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7359
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7358
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7367
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7365
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7369
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7368
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7362
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7367
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7356
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7371
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7381
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7373
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7385
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7374
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7384
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7388
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7385
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7390
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7374
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7390
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7397
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7390
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7395
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7389
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7403
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7382
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7401
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7403
Epoch 41/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7399
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7399
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7402
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7411
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7410
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5330 - accuracy: 0.7400
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7405
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7388
Epoch 49/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7402
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7410

In [42]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5518 - accuracy: 0.7258 - 437ms/epoch - 2ms/step
Loss: 0.5518190860748291, Accuracy: 0.7258309125900269

In [43]:
# Export our model to HDF5 file
nn_model.save("AlphabetSoupCharity5.h5")